= Guided solution (page 1)

. Log in to your lab environment on the **ROLE** platform.

. Break the environment if you have not done it and then step through the fix.

. As the **student** user, run the lab start script on the **workstation** VM to reproduce the issue.
+
[source, bash]
----
cd /home/student/osp_training/scenarios_repo/
./lab start bfx020
----
+
.Sample output
----
[student@workstation scenarios_repo]$ ./lab start bfx020
Running start action against scenario bfx020
Run the following command: 
ssh -i /home/student/osp_training/.scenariobfx020/scenario-bfx020-key.pem cirros@192.168.51.183

[student@workstation scenarios_repo]$ 
----

. Run the ssh command from the previous lab command output and notice the Connection timed out error. Also run the ping command against instance IP.
+
[source, bash]
----
ssh -i /home/student/osp_training/.breakfix020/breakfix020-key.pem cirros@instance.ip.in.your.lab
----
+
[source, bash]
----
ping -c 1 instance.ip.in.your.lab
----
+
NOTE: In the above commands replace the string **instance.ip.in.your.lab** with the **actual IP** address displayed in the output of the lab start script.
+
.Sample output
----
[student@workstation scenarios_repo]$ ssh -i /home/student/osp_training/.scenariobfx020/scenario-bfx020-key.pem cirros@192.168.51.183

ssh: connect to host 192.168.51.183 port 22: Connection timed out
[student@workstation scenarios_repo]$ 
[student@workstation scenarios_repo]$ ping -c 1 192.168.51.183
PING 192.168.51.183 (192.168.51.183) 56(84) bytes of data.

--- 192.168.51.183 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

[student@workstation scenarios_repo]$ 
----
+
You observe that both ping and ssh attempts failed which indicates lack of connectivity.

. Access the RHOSO  environment and determine the specific compute VM where the instance is currently running.
+
[source, bash]
---
oc exec -n openstack openstackclient -- openstack server list --long -c Name -c Status -c Networks -c Host
---
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack server list --long -c Name -c Status -c Networks -c Host

+--------------------+--------+---------------------------------------------------------+---------------------------+
| Name               | Status | Networks                                                | Host                      |
+--------------------+--------+---------------------------------------------------------+---------------------------+
| scenario-bfx020-vm | ACTIVE | scenario-bfx020-network=192.168.120.101, 192.168.51.183 | compute01.srv.example.com |
+--------------------+--------+---------------------------------------------------------+---------------------------+
[student@workstation scenarios_repo]$ 
----
+
* scenario-bfx020-vm is running on the compute01.srv.example.com host.
* Host in the preceding output can differ in your environment.

. Examine the ARP cache to look for the details of the inaccessible OpenStack instance.
+
* The `workstation` machine do not have L2 access to the `192.168.51.0/24` network. 
* To check that you first need to access the `utility` server.
+
[source, bash]
----
ssh lab@utility
ip neighbor | grep instance.ip.in.your.lab
----
+
Replace instance.ip.in.your.lab with actual ip address.
+
.Sample output
----
[student@workstation ~]$ ssh lab@utility
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Fri Mar 28 10:47:30 2025 from 172.25.250.9

[lab@utility ~]$ ip neighbor | grep 192.168.51.183
192.168.51.183 dev eth2 lladdr fa:16:3e:5e:74:ec STALE 
[lab@utility ~]$ 
----
* An entry with the floating IP associated with a MAC address, indicating successful ARP negotiation.
* This signifies functional communication via ARP, but ICMP communication remains problematic.
* Proceed to verify whether the packets are being correctly routed to the appropriate VM.

. Open another terminal and run the ssh command to log in to the compute VM where the instance is hosted.
+
.Sample output
----
[student@workstation ~]$ ssh root@compute01.srv.example.com
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Mon Mar 31 09:31:34 2025 from 192.168.51.254
----

. Run the ovs-vsctl show command on the **compute** node to find the interface associated with the external bridge br-ex.
+
[source, bash]
----
ovs-vsctl show
----
+
.Sample output
----
[root@compute01 ~]# ovs-vsctl show
...output omitted...

    Bridge br-ex
        fail_mode: standalone
        Port patch-provnet-0d56e30d-2f28-44ab-b67a-2fd92f1294bd-to-br-int
            Interface patch-provnet-0d56e30d-2f28-44ab-b67a-2fd92f1294bd-to-br-int
                type: patch
                options: {peer=patch-br-int-to-provnet-0d56e30d-2f28-44ab-b67a-2fd92f1294bd}
        Port br-ex
            Interface br-ex
                type: internal
        Port eth2
            Interface eth2
...output omitted...
----
+
* As per captured output, interface eth2 is associated with br-ex.
* Interface in the preceding output may differ in your environment.

. To verify incoming traffic, initiate a tcpdump on above interface on the compute VM and try to ping the instance from another terminal from the workstation VM.
+
**On compute node:**
+
[source, bash]
----
tcpdump -envvi eth2 icmp
----
+
**On workstation vm:**
+
[source, bash]
----
ping 192.168.51.183 -c 3
----
+
.Sample output
----
[root@compute01 ~]# tcpdump -envvi eth2 icmp
dropped privs to tcpdump
tcpdump: listening on eth2, link-type EN10MB (Ethernet), snapshot length 262144 bytes
07:57:48.601573 52:54:00:02:33:fe > fa:16:3e:5e:74:ec, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 15655, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.51.183: ICMP echo request, id 7, seq 1, length 64
07:57:49.608154 52:54:00:02:33:fe > fa:16:3e:5e:74:ec, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 16610, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.51.183: ICMP echo request, id 7, seq 2, length 64
07:57:50.632466 52:54:00:02:33:fe > fa:16:3e:5e:74:ec, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 17148, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.51.183: ICMP echo request, id 7, seq 3, length 64
[root@compute01 ~]# 


[student@workstation ~]$ ping 192.168.51.183 -c 3
PING 192.168.51.183 (192.168.51.183) 56(84) bytes of data.

--- 192.168.51.183 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2032ms

[student@workstation ~]$ 
----
+
* Observe that ICMP echo requests arriving at the VM.
* The presence of ICMP echo requests reaching the external NIC on the compute VM indicates the proper functioning of the Distributed Virtual Router (DVR).
* However, observe that echo requests are not receiving the echo replies on the workstation VM.

. Determine the tap interface used for the instance on the compute VM.

. Run below command as **student** user on **workstation** vm
+
[source, bash]
----
oc exec -n openstack openstackclient -- openstack port list --server scenario-bfx020-vm
----
+
.Sample output
----
[student@workstation ~]$ oc exec -n openstack openstackclient -- openstack port list --server scenario-bfx020-vm
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                             | Status |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| b3a5ede9-8e32-4bb4-bf75-164857a9d5bc |      | fa:16:3e:7b:72:5e | ip_address='192.168.120.101', subnet_id='e361339e-16a0-4378-af96-7ebae09d6bb0' | ACTIVE |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
[student@workstation ~]$ 
----
+
* The preceding output can differ in your environment.
* The tap interface name is tap<initial part of port ID>. 
* Here tap interface name is tapb3a5ede9-8e
* Determine this for your lab environment.

. Run `ip link show` command for the tap interface on **compute** VM.
+
.Sample output
----
[root@compute01 ~]# ip link show tapb3a5ede9-8e
14: tapb3a5ede9-8e: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1442 qdisc noqueue master ovs-system state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:7b:72:5e brd ff:ff:ff:ff:ff:ff
[root@compute01 ~]# 
----

. Initiate a **tcpdump** on tap interface on the **compute** VM and try to **ping** the instance from another terminal from the **workstation** VM.
+
.Sample output
----
[root@compute01 ~]# tcpdump -envvi tapb3a5ede9-8e
dropped privs to tcpdump
tcpdump: listening on tapb3a5ede9-8e, link-type EN10MB (Ethernet), snapshot length 262144 bytes
08:08:15.375307 fa:16:3e:4a:0e:9b > fa:16:3e:7b:72:5e, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 62, id 12415, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.120.101: ICMP echo request, id 8, seq 1, length 64
08:08:16.424532 fa:16:3e:4a:0e:9b > fa:16:3e:7b:72:5e, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 62, id 13111, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.120.101: ICMP echo request, id 8, seq 2, length 64
08:08:17.448621 fa:16:3e:4a:0e:9b > fa:16:3e:7b:72:5e, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 62, id 13963, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.9 > 192.168.120.101: ICMP echo request, id 8, seq 3, length 64
^C
3 packets captured
3 packets received by filter
0 packets dropped by kernel
[root@compute01 ~]# 


[student@workstation ~]$ ping 192.168.51.183 -c 3
PING 192.168.51.183 (192.168.51.183) 56(84) bytes of data.

--- 192.168.51.183 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2067ms

[student@workstation ~]$ 
----
+
* Successful delivery of the echo request to the tap interface linked with the instance indicates that the network path and connectivity mechanisms are operating correctly.

* All indicators appear satisfactory from the Neutron perspective. The underlying networking infrastructure, including OVN components, is functioning as intended.

* It appeared that the virtual machine (VM) failed to generate a reply when the echo request reached it. 

* The problem might reside within the VM internal configuration or its behavior towards the incoming requests. 

* Access the instance's console for further investigation on this issue.
