= Guided solution (page 1 of 2)

== Objectives
* Investigate the instance connectivity issue in Red Hat OpenStack Platform.
* Solve the instance connectivity in the hands-on lab environment.

== Outcomes
* Investigate why ssh to instance is not working.
* Fix the ssh to instance failing issue.

== Instructions

1. Break the environment if you have not done it and step through the fix.
----
[student@workstation ~]$ ssh student@director
Warning: Permanently added 'director' (ED25519) to the list of known hosts.
student@director's password:
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Fri Jan 26 10:45:39 2024 from 172.25.252.254

[student@director ~]$ sudo su - stack
[sudo] password for student:
Last login: Thu Feb 29 10:37:46 EST 2024 from 172.25.250.9 on pts/0

[stack@director ~]$ source overcloudrc

(overcloud) [stack@director ~]$ lab start bfx020
Running start action against scenario bfx020
Run the following command:
ssh -i /home/stack/osp_training/.scenariobfx020/scenario-bfx020-key.pem cirros@172.25.250.217
----

[NOTE]
====
You need single instance of the lab environment to perorm all the break-fix activities in this series.
====

2. Run the ssh command from the previous lab command output and notice the Connection timed out error. Also run the ping command against instance IP.
----
(overcloud) [stack@director ~]$ ssh -i /home/stack/osp_training/.breakfix020/breakfix020-key.pem cirros@172.25.250.217
ssh: connect to host 172.25.250.217 port 22: Connection timed out

(overcloud) [stack@director ~]$ ping 172.25.250.217 -c 1
PING 172.25.250.217 (172.25.250.217) 56(84) bytes of data.

--- 172.25.250.217 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
----
You observe that both ping and ssh attempts failed which indicates lack of connectivity.

3. Access the overcloud environment and determine the specific compute VM where the instance is currently running.
----
(overcloud) [stack@director ~]$ openstack server list --long -c Name -c Status -c Networks -c Host
+--------------------+--------+---------------------------------------------------------+-------------------------------------+
| Name               | Status | Networks                                                | Host                                |
+--------------------+--------+---------------------------------------------------------+-------------------------------------+
| scenario-bfx020-vm | ACTIVE | scenario-bfx020-network=172.25.250.217, 192.168.120.152 | overcloud-novacompute-1.localdomain |
+--------------------+--------+---------------------------------------------------------+-------------------------------------+
----
Host in the preceding output can differ in your environment.
scenario-bfx020-vm is running on the overcloud-novacompute-1 host.

4. Examine the ARP cache on the director VM and look for the details of the inaccessible OpenStack instance.
----
(overcloud) [stack@director ~]$ ip neighbor | grep 172.25.250.217
172.25.250.217 dev eth0 lladdr fa:16:3e:06:d9:00 STALE
----
An entry with the floating IP associated with a MAC address, indicating successful ARP negotiation.
This signifies functional communication via ARP, but ICMP communication remains problematic.
Proceed to verify whether the packets are being correctly routed to the appropriate VM.

5. Open an another terminal and run the ssh command to log in to the compute VM where the instance is hosted.

Run the ovs-vsctl show command to find the interface associated with the external bridge br-ex.
----
[student@workstation ~]$ ssh student@director
student@director's password:
Activate the web console with: systemctl enable --now cockpit.socket

Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Fri Mar  1 05:04:42 2024 from 172.25.250.9

[student@director ~]$ sudo su - stack
[sudo] password for student:
Last login: Fri Mar  1 05:04:50 EST 2024 on pts/0

(overcloud) [stack@director ~]$ ssh tripleo-admin@overcloud-compute1
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last login: Fri Jan 26 12:15:25 2024 from 172.25.249.11

[tripleo-admin@overcloud-novacompute-1 ~]$ sudo su -

[root@overcloud-novacompute-1 ~]# ovs-vsctl show
...output omitted...
    Bridge br-ex
        fail_mode: standalone
        Port br-ex
            Interface br-ex
                type: internal
        ...output omitted...
        Port ens4
            Interface ens4
...output omitted...
----
Interface in the preceding output can differ in your environment.

6. To verify incoming traffic, initiate a tcpdump on above interface on the compute VM and try to ping the instance from another terminal from the director VM.
----
[root@overcloud-novacompute-1 ~]# tcpdump -envvi ens4 icmp
dropped privs to tcpdump
tcpdump: listening on ens4, link-type EN10MB (Ethernet), snapshot length 262144 bytes
11:04:50.054084 52:54:00:04:fa:0b > fa:16:3e:06:d9:00, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 22810, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.217: ICMP echo request, id 2, seq 1, length 64
11:04:51.095931 52:54:00:04:fa:0b > fa:16:3e:06:d9:00, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 23812, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.217: ICMP echo request, id 2, seq 2, length 64
11:04:52.120036 52:54:00:04:fa:0b > fa:16:3e:06:d9:00, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 23850, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 172.25.250.217: ICMP echo request, id 2, seq 3, length 64
^C
3 packets captured
3 packets received by filter
0 packets dropped by kernel

(overcloud) [stack@director ~]$ ping 172.25.250.217 -c 3
PING 172.25.250.217 (172.25.250.217) 56(84) bytes of data.

--- 172.25.250.217 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2067ms
----
Observe that ICMP echo requests arriving at the VM.

The presence of ICMP echo requests reaching the external NIC on the compute VM indicates the proper functioning of the Distributed Virtual Router (DVR).

However, observe that echo requests are not receiving the echo replies on the director VM.

7. Determine the tap interface used for the instance on the compute VM.
----
(overcloud) [stack@director ~]$ openstack port list --server scenario-bfx020-vm
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| ID                                   | Name | MAC Address       | Fixed IP Addresses                                                             | Status |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
| 32311030-701f-462b-bc64-899e67ad6e78 |      | fa:16:3e:42:bb:e3 | ip_address='192.168.120.152', subnet_id='a587591a-1147-4c49-8d0d-32857a103a82' | ACTIVE |
+--------------------------------------+------+-------------------+--------------------------------------------------------------------------------+--------+
----
The preceding output can differ in your environment.
The tap interface name is tap<initial part of port ID>. Refer to the Additional Information page for more details.
Here tap interface name is tap32311030-70.

8. Run ip l show command on compute VM.
----
[root@overcloud-novacompute-1 ~]# ip l show tap32311030-70
18: tap32311030-70: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1442 qdisc noqueue master ovs-system state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether fe:16:3e:42:bb:e3 brd ff:ff:ff:ff:ff:ff
----

9. Initiate a tcpdump on tap interface on the compute VM and try to ping the instance from another terminal from the director VM.
----
[root@overcloud-novacompute-1 ~]# tcpdump -envvi tap32311030-70
dropped privs to tcpdump
tcpdump: listening on tap32311030-70, link-type EN10MB (Ethernet), snapshot length 262144 bytes
06:06:55.836997 fa:16:3e:34:88:e6 > fa:16:3e:42:bb:e3, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 58088, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 192.168.120.152: ICMP echo request, id 3, seq 1, length 64
06:06:56.855560 fa:16:3e:34:88:e6 > fa:16:3e:42:bb:e3, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 58956, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 192.168.120.152: ICMP echo request, id 3, seq 2, length 64
06:06:57.879456 fa:16:3e:34:88:e6 > fa:16:3e:42:bb:e3, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 59581, offset 0, flags [DF], proto ICMP (1), length 84)
    172.25.250.11 > 192.168.120.152: ICMP echo request, id 3, seq 3, length 64
^C
3 packets captured
3 packets received by filter
0 packets dropped by kernel

(overcloud) [stack@director ~]$ ping 172.25.250.217 -c 3
PING 172.25.250.217 (172.25.250.217) 56(84) bytes of data.

--- 172.25.250.217 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2044ms
----
Successful delivery of the echo request to the tap interface linked with the instance indicates that the network path and connectivity mechanisms are operating correctly.

All indicators appear satisfactory from the Neutron perspective. The underlying networking infrastructure, including OVN components, is functioning as intended.

It appeared that the virtual machine (VM) failed to generate a reply when the echo request reached it. The problem might reside within the VM internal configuration or its behavior towards incoming requests. Access the instance's console for further investigation on this issue.




