= Break-fix Scenario

Objectives:

* Investigate the instance connectivity issue in Red Hat OpenStack Platform.

* Solve the instance connectivity in the hands-on lab environment.

* Familarize with Distributed Virtual Routing (DVR) Functionality.

* Derive the tap interface name.

Scenario: 

Your team manages a Red Hat OpenStack Platform (RHOSP) infrastructure used by an important development team for your company. There was a requirement from your internal networking team to have Open Virtual Network (OVN), an open-source software-defined networking (SDN) solution that seamlessly integrates with OpenStack. Recently networking team noticed that there is connectivity issue with instance running in OpenStack envrionment.

They noticed the following error:

----
[student@workstation ~]$ ssh -i /home/student/osp_training/.scenariobfx020/scenario-bfx020-key.pem cirros@192.168.51.181
ssh: connect to host 192.168.51.181 port 22: Connection timed out
----

In the preceding output, ip address can differ in your lab environment.

== Recreate scenario

. Log in to your lab environment on the ROLE platform.

. As the **student** user, run the lab start script on the **workstation** VM to reproduce the issue.
+
[source, bash]
----
cd /home/student/osp_training/scenarios_repo/
./lab start bfx020
----
+
The lab customization script is already cloned in the **/home/student/osp_training/scenarios_repo/** */ directory.
+
.Sample output
----
[student@workstation ~]$ cd /home/student/osp_training/scenarios_repo/
[student@workstation scenarios_repo]$ ./lab start bfx020
Running start action against scenario bfx020
[WARNING]: Invalid characters were found in group names but not replaced, use
-vvvv to see details
Run the following command: 
ssh -i /home/student/osp_training/.scenariobfx020/scenario-bfx020-key.pem cirros@192.168.51.196

[student@workstation scenarios_repo]$ 
----
+
In the preceding output, IP address can differ in your lab environment.

. This creates an instance with broken ssh connectivity.

. To ensure scenario is recreated, run the ssh command from the previous output:
+
.Sample output
----
[student@workstation scenarios_repo]$ ssh -i /home/student/osp_training/.scenariobfx020/scenario-bfx020-key.pem cirros@192.168.51.196

ssh: connect to host 192.168.51.196 port 22: Connection timed out
[student@workstation scenarios_repo]$ 
----


**IMPORTANT NOTE:**

. If the lab script fails, you will not see the ssh command for instance connectivity.

. Wait a few minutes for the lab to initialize properly, then re-run the lab start script.

. You can retrieve the instance connectivity message generated by the lab script at any time by running the following command.
+
[source, bash]
----
cat ~/osp_training/.scenariobfx019/message
----

. Run the lab finish script if you wish to clean up the environment either to start fresh or to switch to another scenario.
+
[source, bash]
----
cd /home/student/osp_training/scenarios_repo/
./lab finish bfx019
----
